# site settings
title: Populusaurio
email: hola@populusaurio.cl
description: "Lorem ipsum dinosaurios"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" #http://yourdomain.com" # the base hostname & protocol for your site
github_username:  dinosaurio

# social
hashtag: Populusaurio2015
twitter_username: populusaurio
twitter_txt: 'Yo digo sí a la innovación y colaboración...'

# build settings
markdown: kramdown
