# site settings
title: Populusaurio > ¡Comparte!
email: hola@populusaurio.cl
description: "¡Comparte el país que llevas en tu cabeza!"
baseurl: "//difunde.populusaurio.cl" #"//rezzo.github.io/populusaurio/"
url: "" #http://yourdomain.com" # the base hostname & protocol for your site

# social
hashtag: entucabezahayunpais
twitter_username: Populusaurio
twitter_txt: 'Yo digo sí a la innovación y colaboración...'

# build settings
markdown: kramdown
